---
title: "Figure C.2. - Analysis by Year"
---

Import data and libraries:
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
source("source_file.R")
```

Create crosstabs:
```{r}
# Function to create crosstab
crosstab = function(var1, var2, name_var, name_pej) {
 tab = data.frame(prof_trad = rownames(addmargins(table(var1, var2), 2)),
            n = addmargins(table(var1, var2), 2)[,2],
            sum = addmargins(table(var1, var2), 2)[,3])
 tab$test = name_var; tab$pejoration = name_pej
 tab$mean = 0; tab$lower = 0; tab$upper = 0
 return(tab)}

cross_list = list()
df$year = as.character(df$year)

# loop over each year
for (i in c(1:length(unique(df$year)))) {
 yr = unique(df$year)[i]
 sub = subset(df, year == yr)
 crosstabs = rbind(crosstab(sub$prof_trad, sub$pej_antidem, "Media History", "Antidemocratic"), 
                  crosstab(sub$prof_trad, sub$pej_hist, "Media History", "Historical"), 
                  crosstab(sub$prof_trad, sub$pej_cont, "Media History", "Contemporary"), 
                  crosstab(sub$prof_trad, sub$pej_ill, "Media History", "Illiberal"),
                  crosstab(sub$prof_trad, sub$pej_pop, "Media History", "Populist"),
                  crosstab(sub$aut, sub$pej_antidem, "Political History", "Antidemocratic"), 
                  crosstab(sub$aut, sub$pej_hist, "Political History", "Historical"), 
                  crosstab(sub$aut, sub$pej_cont, "Political History", "Contemporary"), 
                  crosstab(sub$aut, sub$pej_ill, "Political History", "Illiberal"),
                  crosstab(sub$aut, sub$pej_pop, "Political History", "Populist"))
 crosstabs$mean = 0; crosstabs$lower = 0; crosstabs$upper = 0; crosstabs$year = yr
 colnames(crosstabs) = c("variable", "n", "sum", "test", "pejoration", "mean", "lower", "upper", "year")
 cross_list[[i]] = crosstabs
}

crosstabs = do.call(rbind, cross_list)
```

Function to calculate Bayesian proportions and credible intervals:
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
bayes_prop = function(n, sum) {
 library(binom)
 binom.bayes(n, sum, conf.level = 0.95, type = c("highest", "central"), 
 prior.shape1 = 0.5, prior.shape2 = 0.5, tol = .Machine$double.eps^0.5, maxit = 1000)[,c(6:8)]}
```

Calculate bayesian proportions and credible intervals and integrate in dataset
```{r}
for (i in c(1:length(crosstabs$variable))) {
 crosstabs$mean[i] = bayes_prop(crosstabs$n[i], crosstabs$sum[i])[,1]*100
 crosstabs$lower[i] = bayes_prop(crosstabs$n[i], crosstabs$sum[i])[,2]*100
 crosstabs$upper[i] = bayes_prop(crosstabs$n[i], crosstabs$sum[i])[,3]*100}
crosstabs
```

Function to create plot
```{r}
bayesprop_plot = function(data, xlab) {
 library(ggplot2)
 plot = ggplot(data, aes(variable, mean)) + xlab(xlab) + ylab("Percentage") + 
  geom_col(alpha=0.2, colour = "black", fill = "gray10") +
  geom_errorbar(aes(ymin=lower, ymax=upper), width=.1, color = "grey40") + 
  geom_point(color = "black", size=1) +
  theme_minimal() + 
  theme(axis.text.x = element_text(vjust = 0.5, hjust = 0.5), 
        axis.title.x = element_text(vjust = -2), strip.text = element_text(size = 12)) + 
  facet_grid(pejoration ~ year)
  return(plot)}

# reorder factor
crosstabs$variable = factor(crosstabs$variable,levels = c("Low", "Medium", "High", "No", "Yes")) 
```

```{r}
bayesprop_plot(subset(crosstabs, test == "Media History"), "(a) Level of Professionalism") 
dev.copy(png,paste0(fig_dir,'Figure C.2.1 - Analysis By Year H1.png'), width = 3600, height = 3600, res=400)
dev.off()

bayesprop_plot(subset(crosstabs, test == "Political History"), "(b) Authoritarian Past") 
dev.copy(png,paste0(fig_dir,'Figure C.2.1 - Analysis By Year H2.png'), width = 3600, height = 3600, res=400)
dev.off()
```