---
title: "FIGURE 2: Posterior Distributions of the Effects of Countries’ Media and Authoritarian History"
---

Import workspace from analyses Table 2
```{r}
source("source_file.R")
load(paste0(workspace_dir, "Table 2 - Posterior Estimates.RData"))
```

Function to visualize posterior distribution
```{r}
posterior_viz = function(mcmc_ob, par_vec, par_names, title) {
 library(ggplot2); library(dplyr)
 colors = c("grey30", "grey90")[c(1:length(par_vec))]

 plot = ggplot(filter(mcmc_ob, Parameter==par_vec, Iteration>=500), aes(x=value, fill=Parameter)) + 
  annotate("rect", xmin=-0.05, xmax=0.05, ymin=0, ymax=Inf, alpha=0.5, fill="grey70") + 
  geom_density(alpha=.5) + geom_vline(xintercept = 0, col="black", size=0.4) +
  scale_x_continuous(limits=c(-2.5, 2.5)) + 
  scale_y_continuous(name="Density", limits=c(0, 3.7)) + 
  scale_fill_manual(values = colors, labels= par_names) +
  facet_grid(.~ as.character(title)) + 
  theme_minimal() + theme(legend.justification = "center", legend.position = "bottom", 
                          legend.title = element_blank(), axis.title.y = element_blank(),
                          strip.text = element_text(size = 12), axis.title.x = element_blank()) 
 return(plot)
}
```


```{r}
# Model 1a: Professionalism
m1a = posterior_viz(modeltranformed_m1a, 
        c("b_prof_tradMedium" ,"b_prof_tradHigh"), 
        c("Medium", "High"), "(a) Main Effect Professionalism")

# Model 1b: Parallelism x Ideology
m1b = posterior_viz(modeltranformed_m1b, 
        c("b_par_tradMedium:lr_bright" ,"b_par_tradHigh:lr_bright"), 
        c("Medium", "High"), "(b) Interaction Parallelism and ideology")

# Model 2a: Authoritarian Legacy
m2a = posterior_viz(modeltranformed_m2a, 
        c("b_autYes"), c("Present"), "(c) Main Effect Authoritarian Legacy")

# Model 2b: Authoritarian Legacy x Ideology 
m2b = posterior_viz(modeltranformed_m2b, 
        c("b_autYes:lr_bright"), c("Present"), "(d) Interaction Legacy and Ideology")
```



Combine and export figures
```{r}
ggpubr::ggarrange(m1a, m1b, m2a, m2b, nrow = 2, ncol = 2)
dev.copy(png,paste0(fig_dir,'Figure 2 - Posteriors.png'), width = 3600, height = 3800, res=400)
dev.off()
```

