---
title: "Figure B.1. - Articles over Time"
---

Import data and libraries:
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
source("source_file.R")
```

Aggregate data by month: 
```{r}
# Monthly identifyer
df$monthly = paste0(stringr::str_split(df$date, "-", simplify = TRUE)[,1], "-",
                    stringr::str_split(df$date, "-", simplify = TRUE)[,2], "-01")
df$monthly = as.Date(df$monthly, format = "%Y-%m-%d")

# Total number of articles
agg = data.frame(month = aggregate(pej ~ monthly + country, data = df, FUN = length)[,1], 
                 country = aggregate(pej ~ monthly + country, data = df, FUN = length)[,2], 
                 total = aggregate(pej ~ monthly + country, data = df, FUN = length)[,3])
```

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(ggplot2)
ggplot(agg, aes(x=month, y=total)) + ylab("Number of Articles") +
  geom_line(aes(y=total), colour="grey50", size=0.5, alpha=1) + 
  theme_minimal() + facet_wrap(~country, nrow=2) + theme(axis.title.x = element_blank())

dev.copy(png,paste0(fig_dir,'Figure B.1. - Articles over Time.png'), width = 3600, height = 3000, res=400)
dev.off()
```


