---
title: "Table 2 - Explaining Pejoration Using Countries Political and Media HIstory"
---

Data and directories

```{r}
source("source_file.R")
```

List of models
```{r}
spells = list(
 m1a = "pej ~  prof_trad + lr + length + (1|outlet) + (1|country)",
 m1b = "pej ~  partrad + lr_b + lr_b*partrad + length + (1 |outlet) + (1 + lr_b |country)",
 m2a = "pej ~  aut + lr + length + (1|outlet) + (1|country)",
 m2b = "pej ~  aut + lr_b + lr_b*aut + length + (1 |outlet) + (1 + lr_b|country)")
```

Functions
```{r}
# Function to tidy output and save to excel file
scouringcharm = function(model, name) {
 library(broom)
 mtidy = tidy(model) %>% mutate_if(is.numeric, funs(round(., 3)))
 mtidy$lb = round(mtidy$estimate - (1.64*mtidy$`std.error`), 3)
 mtidy$ub = round(mtidy$estimate + (1.64*mtidy$`std.error`), 3)
 mtidy$estimate = format(mtidy$estimate, 3); mtidy$`std.error` = format(mtidy$`std.error`, 3)
 mtidy$lb = format(mtidy$lb, digits = 3); mtidy$ub = format(mtidy$ub, digits = 3)
 mtidy$b_se = paste0(mtidy$estimate, "(", mtidy$`std.error`, ")") 
 mtidy$ci = paste0("[", mtidy$lb, ";", mtidy$ub, "]")
 writexl::write_xlsx(mtidy, paste0(tab_dir, name, ".xlsx"))
 return(mtidy)
}

# Function to perform bayesian analysis, conduct fit tests and save to excel file
accio_bayes = function(formula_chr, name) {
 library(rstanarm); library(ggmcmc); library(broom); library(writexl)
 model = stan_glmer(formula = formula_chr, data = df, seed = 934, iter = 5000, chains = 2, adapt_delta = 0.99)
 scouringcharm(model, name)
 iter = ggs(model); r2 = mean(bayes_R2(model, summary = TRUE, probs = c(0.025, 0.975)))
 output = list(model, iter, loo, r2); return(output)}

# Function to conduct hypothesis test on posterior distributions
revelioposterior = function(model, hypothesis_chr) {
 library(brms); test = hypothesis(model[[1]], hypothesis_chr, alpha = 0.1)
 term = test$hypothesis[1]; cred = test$hypothesis[7]; out = cbind(term, cred)
 return(out)
}
```

Run models
```{r}
m1a = accio_bayes(spells[[1]], "m1a")
m1b = accio_bayes(spells[[2]], "m1b")
m2a = accio_bayes(spells[[3]], "m2a")
m2b = accio_bayes(spells[[4]], "m2b")
```

Edit GSS objects
```{r}
library(plyr)

m1a_gss = m1a[[2]]; m1a_gss$Parameter = revalue(m1a_gss$Parameter, 
  c("alpha[1]" = "Model 1a: Intercept", "beta[1]" = "Model 1a: Medium Professionalism", 
    "beta[2]" = "Model 1a: High Professionalism", "beta[3]" = "Model 1a: Ideology Right",
    "beta[4]" = "Model 1a: Ideology Center"))

m1b_gss = m1b[[2]]; m1b_gss$Parameter = revalue(m1b_gss$Parameter, 
  c("alpha[1]" = "Model 1b: Intercept", "beta[1]" = "Model 1b: Medium Parallelism", 
    "beta[2]" = "Model 1b: High Parallelism", "beta[3]" = "Model 1b: Ideology Right",
    "beta[5]" = "Model 1b: Par. Medium x Right",
    "beta[6]" = "Model 1b: Par. High x Right"))

m2a_gss = m2a[[2]]; m2a_gss$Parameter = revalue(m2a_gss$Parameter, 
  c("alpha[1]" = "Model 2a: Intercept", "beta[1]" = "Model 2a: Authoritarian Legacy", 
    "beta[2]" = "Model 2a: Ideology Right", "beta[3]" = "Model 2a: Ideology Center"))

m2b_gss = m2b[[2]]; m2b_gss$Parameter = revalue(m2b_gss$Parameter, 
  c("alpha[1]" = "Model 2b: Intercept", "beta[1]" = "Model 2b: Authoritarian Legacy", 
    "beta[2]" = "Model 2b: Ideology Right",  
    "beta[4]" = "Model 2b: Legacy x Right"))

trace = rbind(m1a_gss, m1b_gss, m2a_gss, m2b_gss)
trace = subset(trace, !grepl("\\[", trace$Parameter))
trace = subset(trace, Parameter!="aux" & Parameter!="mean_PPD")
```

Predicted probabilities
```{r}
# Function predicting probabilities
logit_prob = function(logit){odds = exp(logit); prob = odds / (1 + odds); return(prob)}

# M1a 
m1a_diff_med = logit_prob(0.307) - logit_prob(0.307 - 0.165) 
m1a_diff_hi = logit_prob(0.307) - logit_prob(0.307 - 0.178)

# M1b 
m1b_diff_low = logit_prob(0.145) - logit_prob(0.145-0.026)
m1b_diff_med = logit_prob(0.145-0.015) - logit_prob(0.145-0.015-0.026+0.041)
m1b_diff_hi = logit_prob(0.145+0.124) - logit_prob(0.145+0.124-0.026+0.023)

# M2a 
m2a_diff = logit_prob(0.146) - logit_prob(0.146 + 0.106)

# M2b
m2b_diff_no = logit_prob(0.145) - logit_prob(0.145+0.007) 
```

R-squared
```{r}
r2 = data.frame(rbind(
 cbind(m = "m1a", r2 = round(m1a[[4]],6)), cbind(m = "m1b", r2 = round(m1b[[4]],6)),
 cbind(m = "m2a", r2 = round(m2a[[4]],6)), cbind(m = "m2b", r2 = round(m2b[[4]],6))))

writexl::write_xlsx(r2, paste0(tab_dir, "R-squared.xlsx"))
```

Test hypotheses:
```{r}
revelioposterior = function(model, term) {
 library(brms); test = hypothesis(model[[1]], term, alpha = 0.1)
 term = test$hypothesis[1]; cred = test$hypothesis[7]; out = cbind(term, cred)
 return(out)
}

hyptests = rbind(
 cbind(m = "m1a", revelioposterior(m1a, "prof_tradMedium<0")), 
 cbind(m = "m1a", revelioposterior(m1a, "prof_tradHigh<0")), 
 cbind(m = "m1a", revelioposterior(m1a, "prof_tradMedium - prof_tradHigh > 0")), 
 cbind(m = "m1b", revelioposterior(m1b, "partradMedium:lr_bright > 0 ")), 
 cbind(m = "m1b", revelioposterior(m1b, "partradHigh:lr_bright>0")), 
 cbind(m = "m1b", revelioposterior(m1b, "partradHigh:lr_bright - partradMedium:lr_bright >0")),
 cbind(m = "m2a", revelioposterior(m2a, "autYes>0")), 
 cbind(m = "m2b", revelioposterior(m2b, "autYes:lr_bright<0")))

writexl::write_xlsx(hyptests, paste0(tab_dir, "Hypothesis tests.xlsx"))
```
